### ISSUE TITLE
The code could not run

### ISSUE THREAD

**Issue by maymay1982** [CR-Gjx/LeakGAN#21]
/home/lishaomei/anaconda2/bin/python "/home/lishaomei/LeakGAN-master/Synthetic Data/Main.py"
20
WARNING:tensorflow:From /home/lishaomei/LeakGAN-master/Synthetic Data/Discriminator.py:92: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

(64, ?, 1720)
(?, ?, 1720)
2018-12-27 16:49:16.358266: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-12-27 16:49:16.378827: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2018-12-27 16:49:33.167244: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at mkl_concat_op.cc:814 : Aborted: Operation received an exception:Status: 5, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:811
Traceback (most recent call last):
  File "/home/lishaomei/LeakGAN-master/Synthetic Data/Main.py", line 324, in <module>
    main()
  File "/home/lishaomei/LeakGAN-master/Synthetic Data/Main.py", line 189, in main
    g = sess.run(leakgan.gen_x,feed_dict={leakgan.drop_out:0.8,leakgan.train:1})
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 5, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:811
	 [[node while/feature/FeatureExtractor/concat (defined at /home/lishaomei/LeakGAN-master/Synthetic Data/Discriminator.py:146)  = _MklConcatV2[N=12, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](while/feature/FeatureExtractor/conv-maxpool-1/pool-1, while/feature/FeatureExtractor/conv-maxpool-2/pool-2, while/feature/FeatureExtractor/conv-maxpool-3/pool-3, while/feature/FeatureExtractor/conv-maxpool-4/pool-4, while/feature/FeatureExtractor/conv-maxpool-5/pool-5, while/feature/FeatureExtractor/conv-maxpool-6/pool-6, while/feature/FeatureExtractor/conv-maxpool-7/pool-7, while/feature/FeatureExtractor/conv-maxpool-8/pool-8, while/feature/FeatureExtractor/conv-maxpool-9/pool-9, while/feature/FeatureExtractor/conv-maxpool-10/pool-10, while/feature/FeatureExtractor/conv-maxpool-15/pool-15, while/feature/FeatureExtractor/conv-maxpool-20/pool-20, while/feature/FeatureExtractor/concat/axis, while/feature/FeatureExtractor/conv-maxpool-1/pool-1:2, while/feature/FeatureExtractor/conv-maxpool-2/pool-2:2, while/feature/FeatureExtractor/conv-maxpool-3/pool-3:2, while/feature/FeatureExtractor/conv-maxpool-4/pool-4:2, while/feature/FeatureExtractor/conv-maxpool-5/pool-5:2, while/feature/FeatureExtractor/conv-maxpool-6/pool-6:2, while/feature/FeatureExtractor/conv-maxpool-7/pool-7:2, while/feature/FeatureExtractor/conv-maxpool-8/pool-8:2, while/feature/FeatureExtractor/conv-maxpool-9/pool-9:2, while/feature/FeatureExtractor/conv-maxpool-10/pool-10:2, while/feature/FeatureExtractor/conv-maxpool-15/pool-15:2, while/feature/FeatureExtractor/conv-maxpool-20/pool-20:2, DMT/_51)]]

Caused by op u'while/feature/FeatureExtractor/concat', defined at:
  File "/home/lishaomei/LeakGAN-master/Synthetic Data/Main.py", line 324, in <module>
    main()
  File "/home/lishaomei/LeakGAN-master/Synthetic Data/Main.py", line 177, in main
    learning_rate=LEARNING_RATE)
  File "/home/lishaomei/LeakGAN-master/Synthetic Data/LeakGANModel.py", line 144, in __init__
    gen_o, gen_x,goal,tf.zeros([self.batch_size,self.goal_out_size]),self.goal_init,step_size,gen_real_goal_array,gen_o_worker_array),parallel_iterations=1)
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3291, in while_loop
    return_same_structure)
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3004, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2939, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/lishaomei/LeakGAN-master/Synthetic Data/LeakGANModel.py", line 104, in _g_recurrence
    feature = self.FeatureExtractor_unit(cur_sen,self.drop_out)
  File "/home/lishaomei/LeakGAN-master/Synthetic Data/Discriminator.py", line 146, in unit
    h_pool = tf.concat(pooled_outputs, 3)
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1124, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1033, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/lishaomei/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

AbortedError (see above for traceback): Operation received an exception:Status: 5, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:811
	 [[node while/feature/FeatureExtractor/concat (defined at /home/lishaomei/LeakGAN-master/Synthetic Data/Discriminator.py:146)  = _MklConcatV2[N=12, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](while/feature/FeatureExtractor/conv-maxpool-1/pool-1, while/feature/FeatureExtractor/conv-maxpool-2/pool-2, while/feature/FeatureExtractor/conv-maxpool-3/pool-3, while/feature/FeatureExtractor/conv-maxpool-4/pool-4, while/feature/FeatureExtractor/conv-maxpool-5/pool-5, while/feature/FeatureExtractor/conv-maxpool-6/pool-6, while/feature/FeatureExtractor/conv-maxpool-7/pool-7, while/feature/FeatureExtractor/conv-maxpool-8/pool-8, while/feature/FeatureExtractor/conv-maxpool-9/pool-9, while/feature/FeatureExtractor/conv-maxpool-10/pool-10, while/feature/FeatureExtractor/conv-maxpool-15/pool-15, while/feature/FeatureExtractor/conv-maxpool-20/pool-20, while/feature/FeatureExtractor/concat/axis, while/feature/FeatureExtractor/conv-maxpool-1/pool-1:2, while/feature/FeatureExtractor/conv-maxpool-2/pool-2:2, while/feature/FeatureExtractor/conv-maxpool-3/pool-3:2, while/feature/FeatureExtractor/conv-maxpool-4/pool-4:2, while/feature/FeatureExtractor/conv-maxpool-5/pool-5:2, while/feature/FeatureExtractor/conv-maxpool-6/pool-6:2, while/feature/FeatureExtractor/conv-maxpool-7/pool-7:2, while/feature/FeatureExtractor/conv-maxpool-8/pool-8:2, while/feature/FeatureExtractor/conv-maxpool-9/pool-9:2, while/feature/FeatureExtractor/conv-maxpool-10/pool-10:2, while/feature/FeatureExtractor/conv-maxpool-15/pool-15:2, while/feature/FeatureExtractor/conv-maxpool-20/pool-20:2, DMT/_51)]]

Process finished with exit code 1

**Comment by ssscj** [comment]
I have met the same problem. Have you resolved it, or do you have any idea? Thanks
